#!/usr/bin/env bash

# Update package
sudo apt-get -y update && apt-get -y upgrade && apt-get -y dist-upgrade

# Enable automatic security updates
sudo dpkg-reconfigure --priority=low unattended-upgrades

# Install fail2ban to prevent brute force SSH attacks
sudo apt-get -y install fail2ban

# - - - Setup UFW (Uncomplicated Firewall) rules - - -

# Deny all incoming connections
sudo ufw default deny incoming

# Allow all outgoing connections
sudo ufw default allow outgoing

# Allowed SSH
sudo ufw allow 22/tcp comment ssh

# Allowed HTTP
sudo ufw allow http comment http
sudo ufw allow 80/tcp comment http

# Allowed HTTPS
sudo ufw allow https comment https
sudo ufw allow 443/tcp comment https

# Allowed SFTP
sudo ufw allow sftp comment sftp
sudo ufw allow 115/tcp comment sftp

# Allowed LDAP
sudo ufw allow ldap comment ldap

# Allowed SMTP
sudo ufw allow smtp comment smtp
sudo ufw allow 25 comment smtp

# Allowed IMAP
sudo ufw allow imap comment imap
sudo ufw allow 143 comment imap

# Enable UFW
sudo ufw enable

# To check the status of UFW: 
sudo ufw status verbose
